org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraftVersion=1.21.1
modGroup=com.wolfiy
modId=twitchhud
modName=TwitchHUD
modVersion=1.0.0
modAuthors=Wolfiy
modLicense=All Rights Reserved

fabricLoaderVersion=0.19.5
yarnMappings=1.21.1+build.3
loomVersion=1.18.2

minecraftVersion1211=1.21.11
yarnMappings1211=1.21.11+build.6

minecraftVersion262=26.2

forgeVersion=1.21.1-52.1.16
forgegradleVersion=7.0.40

neoforgeVersion=21.1.251
neoforgeModdevVersion=2.0.147
